[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.4.2"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "go.opencensus.io"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
